- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', files) }}"
  vars:
    files:
      - vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml
      - vars/{{ ansible_os_family }}.yml

- name: Include OS-specific setup tasks
  ansible.builtin.include_tasks: steps/{{ ansible_os_family }}.yml
